[versions]
## Android gradle plugin
androidGradlePlugin = "8.8.0"

## AndroidX
# https://developer.android.com/jetpack/androidx/releases/activity
androidxActivity = "1.9.3"
# https://developer.android.com/jetpack/androidx/releases/core
androidxCoreSplashscreen = "1.0.1"
# https://developer.android.com/jetpack/androidx/releases/lifecycle
androidxLifecycle = "2.8.7"

## Desugar Jdk
# https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md
androidDesugarJdkLibs = "2.1.4"

## Kotlin
# https://github.com/JetBrains/kotlin
kotlin = "2.1.10"

## Test
# https://github.com/junit-team/junit4
junit4 = "4.13.2"
# https://developer.android.com/jetpack/androidx/releases/test?hl=ko
androidxTestExt = "1.2.1"

## Kotlin Symbol Processing
# https://github.com/google/ksp/
ksp = "2.1.10-1.0.30"

kotlinxSerializationJson = "1.7.3"

## Coroutine
# https://github.com/Kotlin/kotlinx.coroutines
coroutine = "1.9.0"

## Compose
# https://developer.android.com/develop/ui/compose/bom/bom-mapping
composeBom = "2024.12.01"
# https://developer.android.com/jetpack/androidx/releases/compose-material3
composeMaterial3 = "1.3.1"
# https://developer.android.com/jetpack/androidx/releases/navigation
androidxComposeNavigation = "2.8.5"

## Hilt
# https://github.com/google/dagger/releases
hilt = "2.54"
# https://developer.android.com/jetpack/androidx/releases/hilt
hiltNavigationCompose = "1.2.0"

## Firebase
# https://firebase.google.com/docs/auth/android/start?hl=ko&_gl=1
googleGms = "4.4.2"
# https://firebase.google.com/docs/android/learn-more?authuser=0&hl=ko&_gl=1#bom
firebaseBoM = "33.7.0"

## Room
# https://developer.android.com/jetpack/androidx/releases/room
room = "2.6.1"

## DataStore
# https://developer.android.com/jetpack/androidx/releases/datastore
datastore = "1.1.1"

## Coil
# https://coil-kt.github.io/coil/
coil = "3.0.4"
coilLegacy = "2.7.0"

## Google identity
# https://developers.google.com/identity/android-credential-manager/releases?hl=ko
googleIdentity = "1.1.1"

## Play Services Location
# https://developers.google.com/android/guides/releases
playServicesLocation = "21.3.0"

## Retrofit
# https://github.com/square/retrofit
retrofit = "2.11.0"
okhttp = "4.12.0"

## Proj4j (좌표 변환)
proj4j = "1.3.0"

## OpenCV
# https://github.com/opencv/opencv/releases
opencv = "4.11.0"




activityKtx = "1.9.3"
appcompat = "1.7.0"
constraintlayout = "2.2.0"
coreKtx = "1.15.0"
fragmentKtx = "1.8.5"
lifecycleViewmodelKtxVersion = "2.8.7"
lifecycleLivedataKtxVersion = "2.8.7"
material = "1.12.0"
navigationFragmentKtx = "2.8.5"
jetbrainsKotlinJvm = "1.9.24"
junit = "4.13.2"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-compiler-gradle-plugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }

junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }

activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtxVersion" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtxVersion" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
material = { module = "com.google.android.material:material", version.ref = "material" }

navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }

kotlin-standard = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxComposeNavigation" }

# Room
androidx-room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# DataStore
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# hilt
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# coil
coil = { module = "io.coil-kt:coil", version.ref = "coilLegacy" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coilLegacy" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutine" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBoM" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx" }

google-android-identity-googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleIdentity" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
opencv = { group = "org.opencv", name = "opencv", version.ref = "opencv" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
proj4j = { group = "org.locationtech.proj4j", name = "proj4j", version.ref = "proj4j" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-kotlin = { id = "org.jetbrains.kotlin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-service-gms = { id = "com.google.gms.google-services", version.ref = "googleGms" }